--
-- Script was generated by Devart dbForge Studio 2020 for MySQL, Version 9.0.897.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 8/5/2022 5:26:41 PM
-- Server version: 8.0.29
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

--
-- Set default database
--
USE db;

--
-- Drop table `employee`
--
DROP TABLE IF EXISTS employee;

--
-- Drop table `office`
--
DROP TABLE IF EXISTS office;

--
-- Set default database
--
USE db;

--
-- Create table `office`
--
CREATE TABLE IF NOT EXISTS office (
  _id varchar(255) NOT NULL DEFAULT '',
  officeCode varchar(255) DEFAULT NULL,
  name varchar(255) DEFAULT NULL,
  address varchar(255) DEFAULT NULL,
  places int DEFAULT NULL,
  PRIMARY KEY (_id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create table `employee`
--
CREATE TABLE IF NOT EXISTS employee (
  _id varchar(255) NOT NULL DEFAULT '',
  createdAt varchar(255) DEFAULT NULL,
  email varchar(255) DEFAULT NULL,
  lastName varchar(255) DEFAULT NULL,
  firstName varchar(255) DEFAULT NULL,
  responsibilities json DEFAULT NULL,
  officeId varchar(255) DEFAULT NULL,
  fired tinyint(1) DEFAULT NULL,
  PRIMARY KEY (_id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS */;